'use strict';
const $ = id => document.getElementById(id);
KO.init();
const t = KO.t, fmt = KO.number, date = KO.kst;
const slope = v => v == null ? '-' : fmt(v*100,4)+t('perCandle');
let data = null, tf = '15m', visible = 100, offset = 0, drag = null;
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function query(){return new URLSearchParams({mode:$('mode').value,...($('mode').value==='replay'?{at:KO.inputUTC($('at').value)}:{})});}
async function get(url){const r=await fetch(url);const j=await r.json();if(!r.ok)throw new Error(typeof j.detail==='string'?j.detail:JSON.stringify(j.detail));return j;}
$('controls').addEventListener('submit',async e=>{e.preventDefault();$('load').disabled=true;$('loading').textContent=t('loading');$('error').hidden=true;try{data=await get('/analysis/btcusdt?'+query());offset=0;render();$('diagnostic-data').textContent='';}catch(err){$('error').textContent=KO.error(err.message);$('error').hidden=false;$('status').textContent=t(data?'previous':'unavailable');}finally{$('load').disabled=false;$('loading').textContent='';}});
$('mode').onchange=()=>{$('at').disabled=$('mode').value==='live';};
function render(){
 $('price').textContent='$'+data.price.toLocaleString('en-US',{minimumFractionDigits:1});$('clock').textContent=date(data.timestamp);$('clock').title=date(data.timestamp,true);$('status').textContent=t(data.data_status)+' · '+t('closedPrice');
 const s=data.scoring.overall;$('score').textContent=KO.signed(s.combined_normalized);$('sr-state').textContent=t(s.state);$('needle').style.left=((s.combined_normalized+1)*50)+'%';
 $('tf-rows').innerHTML=Object.values(data.scoring.timeframes).map(r=>`<details><summary class="row" title="${t('scoreEquation')}"><b>${r.tf}</b><span>${KO.signed(r.normalized)} × ${fmt(r.weight,2)} = ${KO.signed(r.weighted_contribution)}</span></summary><div class="detail">${r.available?'':t('noStructure')+' · '}${t('legacyScore')}: ${KO.signed(r.legacy_score,1)}<br>${t('nearbyCounts')}: ${r.raw_support_count} / ${r.raw_resistance_count}<br>${t('mapCounts')}: ${r.map_support_count} / ${r.map_resistance_count}<br>${t('weightedSides')}: ${fmt(r.weighted_support)} / ${fmt(r.weighted_resistance)}<br>${t('nearestDistances')}: ${KO.percent(r.nearest.support?.distance_pct,3)} / ${KO.percent(r.nearest.resistance?.distance_pct,3)}<br>${t('nativeClose')}: ${date(r.source_close,true)}<table><caption>${t('ageTitle')}</caption><thead><tr><th>${t('age')}</th><th>${t('countSides')}</th><th>${t('weightSides')}</th></tr></thead><tbody>${r.age_buckets.map(b=>`<tr><td>${t(b.age)}</td><td>${b.support_count} / ${b.resistance_count}</td><td>${fmt(b.weighted_support,1)} / ${fmt(b.weighted_resistance,1)}</td></tr>`).join('')}</tbody></table><small>${t('ageNote')}</small></div></details>`).join('');
 $('config').textContent=JSON.stringify(KO.tree({configuration:data.config,hash:data.config_hash,warnings:data.warnings,sources:data.sources}),null,2);
 for(const [name,n] of Object.entries(data.config.swing_ns)){const option=$('scale').querySelector(`option[value="${name}"]`);option.textContent=t(name)+' (N'+n+')';}
 renderSelection();
}
function sideCard(r){const help=t(r.state+'_HELP');return `<div class="side"><small>${t(r.source_type||r.source_side)} ${t('origin')}</small><span class="direction">${t(r.actual_direction||'UNAVAILABLE')}</span><strong>${KO.percent(r.percentile)}<small>${t('percentile')}</small></strong><span class="badge" title="${t('stretchHelp')}">${t(r.state)}</span>${help===r.state+'_HELP'?'':`<small class="state-help">${help}</small>`}<p>${t('ratio')} ${r.stretch_ratio==null?'-':fmt(r.stretch_ratio,2)+t('timesUnit')}<br>${t('slope')} ${slope(r.signed_slope)}<br><span title="${t('resetHelp')}">${t('velocity')} ${fmt(r.velocity,2)}<br>${t('acceleration')} ${fmt(r.acceleration,2)}</span></p><details><summary>${t('calculation')}</summary><div class="detail">${t('sourcePrice')} $${fmt(r.source_price,1)}<br>${t('sourceTime')} ${date(r.source_time,true)}<br>${t('knownAt')} ${date(r.known_at,true)}<br>${t('elapsed')} ${r.elapsed_candles??'-'}<br>${t('median')} ${slope(r.historical_median)}<br>${t('samples')} ${r.sample_count??0}<br>${t('asOf')} ${date(r.observation_time,true)}<br>${t('sourceId')} ${esc(r.source_id||'-')}<br>${t('recentPercentiles')} ${r.recent_percentiles?.map(x=>KO.percent(x,2)).join(' / ')||'-'}<br>${t('quantiles')} ${esc(JSON.stringify(KO.tree(r.quantiles||{})))}</div></details></div>`;}
function renderSelection(){if(!data)return;$('tf-tabs').innerHTML=Object.keys(data.converging).map(t=>`<button type="button" data-tf="${t}" class="${t===tf?'active':''}" aria-pressed="${t===tf}">${t}</button>`).join('');$('tf-tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{tf=b.dataset.tf;offset=0;renderSelection();});
 $('stretch').innerHTML=Object.entries(data.converging[tf]).map(([name,r])=>`<div class="scale-card"><div class="scale-title"><span>${t(name)}</span><span>N${r.n}</span></div><div class="sides">${sideCard(r.high)}${sideCard(r.low)}</div></div>`).join('');
 const scale=$('scale').value;$('state-text').innerHTML=['high','low'].map(side=>`<div class="state-line"><small>${tf} / ${t(scale)} / ${t(side)} ${t('origin')}</small>${esc(KO.message(data.scoring.overall.state,data.converging[tf][scale][side]))}</div>`).join('');
 $('cross-tf').innerHTML=Object.entries(data.converging).map(([frame,r])=>`<div class="cross-row"><b>${frame}</b><span>${t('high')} ${KO.percent(r[scale].high.percentile)} / ${t('low')} ${KO.percent(r[scale].low.percentile)}</span></div>`).join('');$('chart-title').textContent='BTCUSDT · '+tf;draw();}
$('scale').onchange=renderSelection;
function draw(){if(!data)return;const canvas=$('chart'),rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=360*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const w=rect.width,h=360,left=5,right=78,top=25,bottom=26;const all=data.charts[tf];visible=Math.max(15,Math.min(visible,all.length));offset=Math.max(0,Math.min(offset,all.length-visible));const end=all.length-offset,start=Math.max(0,end-visible),rows=all.slice(start,end);let lo=Math.min(...rows.map(r=>r.low)),hi=Math.max(...rows.map(r=>r.high));const pad=(hi-lo)*.08||1;lo-=pad;hi+=pad;const dx=(w-left-right)/rows.length,y=p=>top+(hi-p)/(hi-lo)*(h-top-bottom),x=i=>left+(i+.5)*dx;
 ctx.font='10px Consolas';for(let i=0;i<=4;i++){const p=lo+(hi-lo)*i/4;ctx.strokeStyle='#e1e4db';ctx.beginPath();ctx.moveTo(left,y(p));ctx.lineTo(w-right,y(p));ctx.stroke();ctx.fillStyle='#69716a';ctx.fillText(p.toFixed(0),w-right+8,y(p)+3);}
 rows.forEach((r,i)=>{ctx.strokeStyle=ctx.fillStyle=r.close>=r.open?'#346b55':'#c56b46';ctx.beginPath();ctx.moveTo(x(i),y(r.high));ctx.lineTo(x(i),y(r.low));ctx.stroke();ctx.fillRect(x(i)-Math.max(1,dx*.3),Math.min(y(r.open),y(r.close)),Math.max(2,dx*.6),Math.max(1,Math.abs(y(r.close)-y(r.open))));});
 const horizontal=(p,color,label)=>{if(p==null||p<lo||p>hi)return;ctx.setLineDash([4,4]);ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(0,y(p));ctx.lineTo(w-right,y(p));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=color;ctx.fillText(label+' '+p.toFixed(1),8,y(p)-5);};horizontal(data.price,'#24302e','15m '+t('currentPrice'));
 if($('overlays').checked){const r=data.scoring.timeframes[tf];horizontal(r.nearest.support?.price,'#ba541d',t('SUPPORT'));horizontal(r.nearest.resistance?.price,'#3b6e91',t('RESISTANCE'));const selected=data.converging[tf][$('scale').value];for(const side of ['high','low']){const s=selected[side];if(s.source_price==null)continue;horizontal(s.source_price,'#8a7b59',t(side));const i=rows.findIndex(c=>c.open_time===s.source_time),last=rows.findIndex(c=>c.close_time+1===s.observation_time);if(i>=0&&last>=0){ctx.strokeStyle='#8a7b59';ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(x(i),y(s.source_price));ctx.lineTo(x(last),y(rows[last].close));ctx.stroke();ctx.setLineDash([]);}}}
 ctx.fillStyle='#69716a';ctx.fillText(date(rows[0].open_time),5,w<480?h-16:h-4);ctx.fillText(date(rows.at(-1).open_time),w<480?5:Math.max(10,w-240),h-4);canvas._view={rows,dx,left};}
$('chart').addEventListener('wheel',e=>{e.preventDefault();visible+=e.deltaY>0?15:-15;draw();},{passive:false});$('chart').onpointerdown=e=>{drag={x:e.clientX,offset};$('chart').setPointerCapture(e.pointerId);};$('chart').onpointerup=()=>drag=null;$('chart').onpointercancel=()=>drag=null;
$('chart').onpointermove=e=>{const v=$('chart')._view;if(!v)return;if(drag){offset=Math.round(drag.offset+(e.clientX-drag.x)/v.dx);draw();}const i=Math.floor((e.clientX-$('chart').getBoundingClientRect().left-v.left)/v.dx),r=v.rows[i];if(r)$('hover').textContent=`${date(r.open_time)} · ${t('open')} ${r.open} ${t('highPrice')} ${r.high} ${t('lowPrice')} ${r.low} ${t('close')} ${r.close}`;};
$('overlays').onchange=draw;$('zoom-in').onclick=()=>{visible-=20;draw();};$('zoom-out').onclick=()=>{visible+=20;draw();};$('reset').onclick=()=>{visible=100;offset=0;draw();};new ResizeObserver(draw).observe($('chart'));
$('diagnostics').onclick=async()=>{if(!data)return;$('diagnostics').disabled=true;$('diagnostic-data').textContent=t('diagnosticsLoading');try{const q=new URLSearchParams({tf,scale:$('scale').value,at:new Date(data.timestamp).toISOString()});$('diagnostic-data').textContent=JSON.stringify(KO.tree(await get('/analysis/btcusdt/diagnostics?'+q)),null,2);}catch(e){$('diagnostic-data').textContent=KO.error(e.message);}finally{$('diagnostics').disabled=false;}};
$('controls').requestSubmit();
